version: "3"
services:
  dspace:
    command: start --debug
    environment:
      JPDA_ADDRESS: "0.0.0.0:8000"
      JPDA_TRANSPORT: "dt_socket"
      #This property must be used in the 'java' invocation inside de 'dspace_dir/bin/dspace' bash file. 
      #I.e. replace the last line with 'java $JPDA_CLI_OPTS $JAVA_OPTS ... org.dspace.app.launcher.ScriptLauncher "$@"'
      JPDA_CLI_OPTS: "-Xdebug -Xnoagent -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8001"
    ports:
      - "8000:8000"
      - "8001:8001"
      - "5005:5005"
