version: "3"
#services:
#  pgadmin4:
#     image: dpage/pgadmin4
#     environment:
#       PGADMIN_DEFAULT_EMAIL: "user@dspace.com"
#       PGADMIN_DEFAULT_PASSWORD: "dspace"
#     restart: unless-stopped
#     ports:
#       - "80:80"
